version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prices
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  service:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - RPC_URL=${RPC_URL}
      - CMC_API_KEY=${CMC_API_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres-data:
